-- SCRIPT DE CRÉATION DES TABLES FINALES
-- ce script assure la création des tables définitives de la base de données
-- ainsi que l'insertion des données issues de tmp_mad_donnees au sein de celles-ci

begin;

-- nécessaire afin de ne pas avoir à marquer le nom de la table et du schéma à chaque partie de la requête
set search_path to madata_db;

-- suppression des tables avec clés étrangères en cas d'itération
drop table if exists SEANCES cascade ;
drop table if exists ACTIVITES cascade ;
drop table if exists BILAN_ANNUEL_SDP ;
drop table if exists BILAN_SEANCES ; 

-- 1. création d'abord des tables nécessaires à la réalisation d'autres tables (avec des PK mais sans FK)

-- création de la table salles
create table if not exists SALLES (
	id_salle integer generated by default as identity primary key, -- génération automatique de l'id
	nom_salle varchar(50)
	);

-- suppression d'éléments pouvant avoir été gardé lors d'itérations
truncate table SALLES ;

-- insertion des données de la table après s'être assuré qu'elle est vide
insert into SALLES(nom_salle)
select distinct salles as nom_salle -- 'select distinct' car on ne veut pas de doublons
from TMP_MAD_DONNEES ;

create table if not exists GROUPES (
	id_groupe integer generated by default as identity primary key,
	reservation varchar,
	nom_client varchar, -- nom_client anonymisé par compliance RGPD. Possibilité de réduire le nom à une seule lettre ou chiffre pour limiter les doublons ?
	nature_client varchar,
	-- suppression de categorie_client qui n'apportait aucun élément supplémentaire
	type_client varchar,
	ville varchar,
	pays varchar,
	code_postal varchar,
	langue varchar -- valeur bien vide, utilité ?
);

truncate table GROUPES ;

insert into GROUPES (reservation, nom_client, nature_client, type_client, ville, pays, code_postal, langue)
select distinct
reservation,
nom_client,
nature_client,
type_client,
ville,
pays,
code_postal,
langue_activite
from tmp_mad_donnees
where reservation is not null;

-- création de la table publics
create table if not exists PUBLICS (
	id_public integer generated by default as identity primary key,
	type_public varchar
);

-- suppression d'éléments pour itération
truncate table PUBLICS ;

-- insertion des valeurs
insert into PUBLICS(type_public)
select distinct 
	type_public
from tmp_mad_donnees;

-- création de la table expositions
create table if not exists EXPOSITIONS (
	id_exposition varchar(10) primary key,
	nom_exposition varchar(50)
	);

truncate table EXPOSITIONS ;

-- insertion des valeurs
insert into EXPOSITIONS(id_exposition, nom_exposition)
select distinct 
 	-- l'id_seance comprend déjà un id spécifique pour chaque exposition, il suffit de l'extraire
	substring(id_seance_complet,18,3) as id_exposition, -- extraction réalisée avec substring() et la position des caractères
	exposition as nom_exposition
from tmp_mad_donnees;

-- création de la table activites
create table ACTIVITES (
	id_activite varchar(10) primary key,
	type_activite varchar(50) not null
);

truncate table ACTIVITES ;

insert into ACTIVITES(id_activite, type_activite)
select distinct 
	-- comme pour EXPOSITIONS, il suffit de s'appuyer sur id_seance pour réaliser l'id_activite
	substring(id_seance_complet,15,2) as id_activite, -- extraction réalisée avec substring() et la position des caractères
	type_activite as type_activite
from tmp_mad_donnees
where type_activite is not null;

-- création de la table FREQUENTATION_MDF_2024
create table if not exists FREQUENTATION_MDF_2024 (
	-- Ajout des données du jeu #3, 'wikidata_mdf'
	LIEN_WIKIDATA VARCHAR(20), 
	ID_MUSEOFILE VARCHAR(20) PRIMARY KEY,
	NOM_MUSEE VARCHAR(300),
	VILLE VARCHAR(100),
	DESCRIPTION TEXT,
	LABEL_TH VARCHAR(100),
	ACCESSIBILITE_PMR TEXT,
	
	-- Ajout des données du jeu #4, 'frequentation_mdf'
	PAYANT INTEGER,
	GRATUIT INTEGER,
	TOTAL INTEGER,
	INDIVIDUEL INTEGER,
	SCOLAIRES INTEGER,
	GROUPES_HORS_SCOLAIRES INTEGER,
	MOINS_18_HORS_SCOLAIRE INTEGER,
	VISITEURS_18_25 INTEGER
);

truncate table FREQUENTATION_MDF_2024 ;

insert into FREQUENTATION_MDF_2024 (LIEN_WIKIDATA, ID_MUSEOFILE, NOM_MUSEE, VILLE, DESCRIPTION, LABEL_TH, ACCESSIBILITE_PMR, PAYANT, GRATUIT, TOTAL, INDIVIDUEL, SCOLAIRES, GROUPES_HORS_SCOLAIRES, 
 MOINS_18_HORS_SCOLAIRE, VISITEURS_18_25)
select distinct on (ID_MUSEOFILE)
	LIEN_WIKIDATA, 
	ID_MUSEOFILE,
	NOM_MUSEE,
	VILLE,
	DESCRIPTION,
	LABEL_TH,
	ACCESSIBILITE_PMR,
	PAYANT,
	GRATUIT,
	TOTAL,
	INDIVIDUEL,
	SCOLAIRES,
	GROUPES_HORS_SCOLAIRES,
	MOINS_18_HORS_SCOLAIRE,
	VISITEURS_18_25
from TMP_DONNEES_EXTERNES;

-- 2. création ensuite des tables nécessitant des relations avec des tables pré-existantes (avec FK et parfois PK).
-- Elles sont rangées logiquement afin d'éviter des conflits (la table avec PK doit exister avant d'être appelée en FK).

-- création de la table seances
create table if not exists SEANCES (
	id_seance varchar primary key,
	id_exposition varchar(50) references expositions(id_exposition),
	id_activite varchar(10) references activites(id_activite),
	langue_seance varchar(10),
	date_seance date not null,
	heure_debut time,
	heure_fin time,
	nature_seance varchar(50)
	);

truncate table SEANCES ;

insert into SEANCES(id_seance, id_activite, id_exposition, langue_seance, date_seance, heure_debut, heure_fin, nature_seance)
select distinct
	id_seance_complet as id_seance,
	substring(id_seance_complet,15,2) as id_activite,
	substring(id_seance_complet,18,3) as id_exposition,
	langue_activite as langue_seance,
	date_seance,
	heure_debut,
	heure_fin,
	case
		when nature_seance = 'A' then 'réservation en ligne'
		when nature_seance = 'G' then 'réservation en groupe'
		else null
	end as nature_seance
from tmp_mad_donnees;

-- création de la table billets
create table if not exists BILLETS (
	id_billet integer generated by default as identity primary key,
	numero_billet varchar(100),
	nom_client varchar(100),
	id_seance varchar references SEANCES(id_seance),
	tarif varchar,
	-- etat varchar(10),
	numero_operation varchar,
	date_creation date,
	heure_operation time
	);

truncate table BILLETS ;

insert into BILLETS(numero_billet, nom_client, id_seance, tarif, numero_operation, date_creation, heure_operation) -- etat à ajouter
select distinct 
	numero_billet,
	nom_client,
	id_seance_complet as id_seance,
	tarif,
	-- etat à ajouter ?
	num_operation_billet,
	date_creation_billet,
	heure_operation_billet
from tmp_mad_donnees
where numero_billet is not null; -- important pour que chaque entrée soit bien associée à un billet existant

-- création de la table capacite
create table if not exists CAPACITE (
	id_seance varchar references SEANCES(id_seance),
	places_ouvertes integer,
	places_vendues integer,
	places_disponibles integer,
	overbooking integer,
	overbooking_vendu integer,
	taux_remplissage real
	);

truncate table CAPACITE ;

insert into CAPACITE (id_seance, places_ouvertes, places_vendues, places_disponibles, overbooking,
overbooking_vendu, taux_remplissage)
select distinct 
	id_seance_complet as id_seance,
	places_ouvertes,
	places_vendues,
	places_disponibles,
	overbooking,
	overbooking_vendu,
	taux_remplissage
from tmp_mad_donnees;

-- creation de la table BILAN_ANNUEL_SDP
create table if not exists BILAN_ANNUEL_SDP (
    id_bilan_annuel integer generated by default as identity primary key,
    id_museofile VARCHAR(20) references FREQUENTATION_MDF_2024(id_museofile),
    annee INTEGER NOT NULL, 
    
    -- Données agrégées, faisant le bilan des activités du SDP à partir des csv fournis
    nb_seances INTEGER,
    nb_billets INTEGER,
    nb_expositions INTEGER,
    nb_activites INTEGER
);

truncate table BILAN_ANNUEL_SDP ;

insert into BILAN_ANNUEL_SDP (id_museofile, annee, nb_seances, nb_billets, 
nb_expositions, nb_activites  
)

select 
    'M5021', -- identifiant museofile du MAD
    EXTRACT(YEAR FROM s.date_seance) AS annee, -- extrait l'année de la date de la séance
    count(distinct s.id_seance), 
    count(distinct b.numero_billet),
    count(distinct s.id_exposition), 
    count(distinct s.id_activite) 
-- jointure entre les tables seances et billets
from SEANCES s
left join BILLETS b on s.id_seance = b.id_seance
where EXTRACT(year from s.date_seance) in (2024, 2025, 2026)
group by EXTRACT(year from s.date_seance);

-- fin du script SQL
commit ;
